---
- hosts: database
  become: true
  tasks: 

    - name: Touch a file in  /mnt/mysql_backups/database_list.txt
      lineinfile:
        path: /mnt/mysql_backups/database_list.txt
        line: dev,test,qa,prod 
        create: yes
  


    - name: created and stored in /mnt/mysql_backups/archive.gz
      archive:
        path: /mnt/mysql_backups/database_list.txt 
        dest: /etc/motd/archive1.gz
        format: gz


