---
- hosts: database
  become: true
  tasks:
    - name: create a directory fact.d
      file:
        path: /etc/ansible/facts.d
        state: directory
        recurse: yes

    - name: touch a file  
      file:
        path: /etc/ansible/facts.d/custom.fact
        state: touch


    - name: Copy using inline content
      copy:
        content: |
          [sample_rhce]
          server_role=mysql
        dest: /etc/ansible/facts.d/custom.fact
 

    - name: Print the custom facts value
      debug:
        msg: "{{ ansible_local.custom.sample_rhce }}"

    

