---
- hosts: database
  become: true
  tasks:
    - name: Create a directory if it does not exist
      file:
        path: /etc/ansible/facts.d
        state: directory
        recurse: yes


    - name: touch file custom fact
      file:
        path: /etc/ansible/facts.d/custom.fact
        state: touch


    - name: Copy using inline content
      copy:
        content: |
          [sample_exam]
          server_role=mysql 

        dest: /etc/ansible/facts.d/custom.fact

    - name: check the debug messages 
      debug:
        msg: "{{ansible_local.custom.sample_rhce }}"
