---
- hosts: proxy
  become: true
  roles:
    - geerlingguy.haproxy
  vars_files:
    - vars/haproxy.yml
  tasks:
    - name: ensure firewall is enable and started
      systemd:
        name: firewalld
        state: started
        enabled: yes


    - name: open port 80 
      firewalld:
        port: 80/tcp
        permanent: yes
        immediate: yes
        state: enabled


