- hosts: database
  become: true
  tasks:
    - name: "create mysql repositoy for database server"
      yum_repository:
        name: mysql80-community
        description: MySQL 8.0 YUM Repo
        baseurl: http://repo.mysql.com/yum/mysql-8.0-community/el/8/x86_64/
        gpgcheck: yes
        enabled: yes
        gpgkey: http://repo.mysql.com/RPM-GPG-KEY-mysql
